spring:
  cloud:
    gateway:
      routes:
        - id: user-login
          uri: http://localhost:8084
          predicates:
            - Path=/web/login/**
        - id : user-signup
          uri: http://localhost:8084
          predicates:
            - Path=/web/signup/**
        - id : user-homepage
          uri: http://localhost:8084
          predicates:
            - Path=/web
        - id: admin
          uri: http://localhost:8084
          predicates:
            - Path=/web/admin/**
        - id: dispatcher-upload
          uri: http://localhost:8082
          predicates:
            - Path=/web/upload/**
          filters:
            - AuthenticationFilter
        - id: documents
          uri: http://localhost:8085
          predicates:
            - Path=/web/documents/**
          filters:
            - AuthenticationFilter
user-service:
  uri: http://localhost:8084/api
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE