spring:
  cloud:
    gateway:
      routes:
        - id: user-login
          uri: http://localhost:8084
          predicates:
            - Path=/web/login
            - Path=/web/signup
            - Path=/web
        - id: dispatcher-upload
          uri: http://localhost:8082
          predicates:
            - Path=/upload/**
            - Path=/web/upload
          filters:
            - AuthenticationFilter
        - id: documents
          uri: http://localhost:8085
          predicates:
            - Path=/documents/**
          filters:
            - AuthenticationFilter
user-service:
  uri: http://localhost:8084